#!/usr/bin/env bash
#install haproxy as load balancer and configure it to direct traffic

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen load_balancer 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption forwardfor\n\toption httpclose\n\tserver 13974-web-01 	3.230.155.52 check\n\tserver 13974-web-01 18.207.130.236 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
